src/Entity/Medicament.php
<?php

namespace App\Entity;

use App\Repository\MedicamentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MedicamentRepository::class)
 */
class Medicament
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $substance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSubstance(): ?string
    {
        return $this->substance;
    }

    public function setSubstance(string $substance): self
    {
        $this->substance = $substance;

        return $this;
    }
}

src/Entity/Medicaments.php
<?php

namespace App\Entity;

use App\Repository\MedicamentsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MedicamentsRepository::class)
 */
class Medicaments
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_commercial;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2, nullable=true)
     */
    private $Prix_Echantion;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contre_indication;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $effet;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_med;

    public function getId(): ?int
    {
        return $this->id;
    }
    
  

    public function getNomCommercial(): ?string
    {
        return $this->nom_commercial;
    }

    public function setNomCommercial(string $nom_commercial): self
    {
        $this->nom_commercial = $nom_commercial;

        return $this;
    }

    public function getPrixEchantion(): ?string
    {
        return $this->Prix_Echantion;
    }

    public function setPrixEchantion(?string $Prix_Echantion): self
    {
        $this->Prix_Echantion = $Prix_Echantion;

        return $this;
    }

    public function getContreIndication(): ?string
    {
        return $this->contre_indication;
    }

    public function setContreIndication(?string $contre_indication): self
    {
        $this->contre_indication = $contre_indication;

        return $this;
    }

    public function getEffet(): ?string
    {
        return $this->effet;
    }

    public function setEffet(?string $effet): self
    {
        $this->effet = $effet;

        return $this;
    }

    public function getImageMed(): ?string
    {
        return $this->image_med;
    }

    public function setImageMed(?string $image_med): self
    {
        $this->image_med = $image_med;

        return $this;
    }
}

src/Form/MedicamentsType.php
<?php

namespace App\Form;

use App\Entity\Medicaments;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class MedicamentsType extends AbstractType
{
     /**
     * permet d'avoir la configuration de base d'un champ !
     *
     * @param string $label
     * @param string $placeholder
     * @return array
     */
    private function getConfiguration($label, $placeholder){
        return [
            'label' => $label, 
            'attr' => [
                'placeholder' => $placeholder
            ]
        ];

    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_commercial',TextType::class, $this->getConfiguration("nom commercial", "tapez un nom commercial"))
            ->add('Prix_Echantion',TextType::class, $this->getConfiguration("Prix échantion", "tapez un Prix"))
            ->add('contre_indication',TextType::class, $this->getConfiguration("contre indication", "tapez une contre indication"))
            ->add('effet',TextType::class, $this->getConfiguration("Effet", "tapez un effet"))
            ->add('imageMed', UrlType::class, $this->getConfiguration("URL de l'image", "tapez l'url de l'image"))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Medicaments::class,
        ]);
    }
}

src/Controller/MedicamentController.php
<?php

namespace App\Controller;

use App\Entity\Medicaments;
use App\Form\MedicamentsType;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\MedicamentsRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class MedicamentController extends AbstractController
{
    /**
     * @Route("/medicament", name="medicament_liste")
     */
    public function index(MedicamentsRepository $repo): Response
    {
        $medicaments = $repo->findAll();
        return $this->render('medicament/medicament.html.twig', [
            'medicaments' => $medicaments,
        ]);

 
    }
           /**
     * Permet d'afficher une seule famille 
     * 
     *@Route("/medicament/{nom_commercial}", name="medicament_show") 
     *
     * @return Response 
     */
    public function show(Medicaments $medicament)
    {
            

        return $this->render('medicament/show1.html.twig', [
            'medicament' => $medicament
        ]);
    
    }
     /**
     * Permet de créer un medicament 
     *
     * @Route("/medicaments/new", name="medicament_create")
     * 
     * @return void
     */
    public function create(Request $request, EntityManagerInterface $manager) 
    {
        $medicament = new Medicaments();


        $form = $this->createForm(MedicamentsType::class, $medicament);

        $form->handleRequest($request);


        if($form->isSubmitted() && $form->isValid()){
            
            $manager->persist($medicament);
            $manager->flush();
            $this->addFlash(
                'success',
                "L'annonce <strong>Test</strong> a bien été enregistrée !"
            ); 
         

            return $this->redirectToRoute('medicament_show', [
                   'nom_commercial' => $medicament->getNomCommercial()
            ]);

        }
                      

        return $this->render('Medicament/new.html.twig', [
            'form' => $form->createView()
        ]);
        }
    
    
        /* @Route("/delete/{id}" , name="medicament_delete")
        */
       public function deleteAction($id) {
        $medicament = $this->MedicamentsRepository->findOrFail($id);
        $medicament->delete();
   
       }
}

templates/medicament/medicament.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos medicaments{% endblock %}

{% block body %}
<div class="container">
   <h1 class="my-3">Voici nos médicaments !</h1>

         
      <div class="row">
         {% for medicaments in medicaments%} 
              {% set url = path('medicament_show', {'nom_commercial': medicaments.nomCommercial}) %}

            <div class="col-md-4">
               <div class="card bg-light mb-1">
                  <a href="{{ url }}">
                     <img src="{{medicaments.imageMed}}" alt="Image du composant"style="height: 200px; width: 100%; display: block;">
                  </a>
                       <div class="card-body">
                        <h4 class="card-text">
                           <a href="{{ url }} ">
                              {{medicaments.nomCommercial}}
                           </a>                  
                        <a href="{{path('composants_liste')}}" class="btn btn-secondary"> voir les composants !</a>
                        <td> <a href="delete-medicaments/{{ medicaments.id }}" class="btn btn-secondary"> supprimer</a></td>
                       
                     </div>
               </div>
            </div>

        {% endfor %}
     </div>
</div>
{% endblock %}

templates/medicament/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un medicament{% endblock %}

{%form_theme form _self %}

{% block body %} 

        <div class="container">
            <h1>Ajouter un nouveau médicament</h1>

            {{ form_start(form) }}

            
            {{ form_widget(form) }}

            <button type="submit" class="btn btn-primary">Ajouter le nouveau médicament</button>

            {{form_end(form)}}
        </div>


 {% endblock %}

  

templates/medicament/show1.html.twig
    {% extends 'base.html.twig' %}

    {% block title %}
            {{medicament.nomCommercial}}
    {% endblock %}

    {% block body %}

    <div class="ad-title" style="background-image: url({{medicament.nomCommercial}})">
        <div class="container">
            <h1>{{medicament.nomCommercial}}</h1>
                 <p class="h2">
                       {{medicament.PrixEchantion}}&euro;</strong>
                     
                     </p>
                  </div>
                    
           
        </div>

    </div>
    <div class="container">
    <div class="row">
        <div class="col-md-8 mb-3">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
        <img class="d-block w-100" src="https://static4.depositphotos.com/1006463/360/i/600/depositphotos_3601033-stock-photo-3d-pills-render-onwhite-background.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
        <img class="d-block w-100" src="https://leblogmedical.fr/wp-content/uploads/2012/06/medicament.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
        <img class="d-block w-100" src="https://www.francenetinfos.com/wp-content/uploads/2015/12/medicament-en-ligne.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    </div>
    </div> 
    </div>
        <div class="col">
            <div class="row">
            
                <div class="col">
                <h3>informations sur le medicament </h3>
                <spn class="badge badge-primary">type de medicaments</spn>
                </div>
                <div class="row">
           <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Et, id optio. Unde ipsa accusantium, vero ratione enim exercitationem? Doloribus, quis.</p>
           <p>Facilis consequatur numquam eius quos rerum laudantium fugit magnam, culpa delectus minus officia, sequi, in sunt et aperiam facere similique?</p>
           <p>Id nostrum quaerat laboriosam in voluptatem ipsa omnis labore aliquam, neque perspiciatis repudiandae praesentium reprehenderit dicta maiores delectus eius ratione.</p>
 </div>
  <a href="#" class="btn btn-primary">Acheter !</a>
            
            </div>
        
        </div>
    </div>
</div>

    {% endblock %}