src/Entity/Famille.php
<?php

namespace App\Entity;

use App\Repository\FamilleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FamilleRepository::class)
 */
class Famille
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_famille;

<<<<<<< HEAD
=======
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_fml;

>>>>>>> laïdine
    public function getId(): ?int
    {
        return $this->id;
    }
 

    public function getNomFamille(): ?string
    {
        return $this->nom_famille;
    }

    public function setNomFamille(string $nom_famille): self
    {
        $this->nom_famille = $nom_famille;

        return $this;
    }
<<<<<<< HEAD
=======

    public function getImageFml(): ?string
    {
        return $this->image_fml;
    }

    public function setImageFml(?string $image_fml): self
    {
        $this->image_fml = $image_fml;

        return $this;
    }
>>>>>>> laïdine
}

src/Controller/FamilleController.php
<?php

namespace App\Controller;

use App\Entity\Famille;
use App\Repository\FamilleRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FamilleController extends AbstractController
{
    /**
     * @Route("/famille", name="famille_liste")
     */
    public function index(FamilleRepository $repo): Response
    {
        $familles = $repo->findAll();
        return $this->render('famille/famille.html.twig', [
            'familles' => $familles,
        ]);
    }
    /**
     * Permet d'afficher une seule famille 
     * 
     *@Route("/famille/{nom_famille}", name="famille_show") 
     *
     * @return Response 
     */
    public function show(Famille $famille){
            

        return $this->render('famille/show.html.twig', [
            'famille' => $famille
        ]);
    
}

}

   

templates/famille/famille.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos familles{% endblock %}

{% block body %}
<div class="container">
   <h1 class="my-3">Voici les familles de nos médicaments !</h1>

      
      <div class="row">
         {% for famille in familles %} 
         
            
              {% set url = path('famille_show', {'nom_famille': famille.nomFamille}) %}

            <div class="col-md-4">
               <div class="card bg-light mb-1">
                  <a href="{{path('medicament_liste')}}">
                     <img src=" {{famille.imageFml}}" alt="Image du composant"style="height: 200px; width: 100%; display: block;">
                  </a>
                       <div class="card-body">
                        <h4 class="card-text">
                           <a href="{{path('medicament_liste')}}">
                              {{famille.nomFamille}}
                           </a>                  
                        <a href="{{ url }}" class="btn btn-secondary"> En savoir plus !</a>
                     </div>
               </div>
            </div>
         
        {% endfor %}
     </div>
</div>


{% endblock %}

templates/famille/show.html.twig
    {% extends 'base.html.twig' %}

    {% block title %}
            {{famille.nomFamille}}
    {% endblock %}

    {% block body %}

    <div class="ad-title" style="background-image: url({{famille.nomFamille}})">
        <div class="container">
            <h1>{{famille.nomFamille}}</h1>
                
                    
           
        </div>

    </div>
    <div class="container">
    <div class="row">
        <div class="col-md-8 mb-3">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
        <img class="d-block w-100" src="https://i.la-croix.com/729x486/smart/2014/02/14/1106656/Faut-avoir-peur-homme-augmente_0.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
        <img class="d-block w-100" src="https://gabon-info.ga/wp-content/uploads/2020/07/prescrire-medicaents-liste_0ab26f7dda7e468b05c4a763a4c7aba0.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
        <img class="d-block w-100" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToptbNefY51KGR1BmdO7ZeqEno0KmpldjTVIInysXPNqH4o8jGbsNKQuY2Sutjm0WQ0t0&usqp=CAU" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    </div>
    </div> 
    </div>
        <div class="col">
            <div class="row">
            
                <div class="col">
                <h3>informations sur la famille </h3>
                <spn class="badge badge-primary">type de medicaments</spn>
                </div>
                <div class="row">
           <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Et, id optio. Unde ipsa accusantium, vero ratione enim exercitationem? Doloribus, quis.</p>
           <p>Facilis consequatur numquam eius quos rerum laudantium fugit magnam, culpa delectus minus officia, sequi, in sunt et aperiam facere similique?</p>
           <p>Id nostrum quaerat laboriosam in voluptatem ipsa omnis labore aliquam, neque perspiciatis repudiandae praesentium reprehenderit dicta maiores delectus eius ratione.</p>
 </div>
            
            </div>
        
        </div>
    </div>
</div>

    {% endblock %}