src/Entity/Composant.php
<?php

namespace App\Entity;

use App\Entity\Image;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ComposantRepository;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass=ComposantRepository::class)
 */
class Composant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_composant;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }
 

    public function getNomComposant(): ?string
    {
        return $this->nom_composant;
    }

    public function setNomComposant(string $nom_composant): self
    {
        $this->nom_composant = $nom_composant;

        return $this;
    }
    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
    

}

src/Controller/ComposantController.php
<?php

namespace App\Controller;

use App\Repository\ComposantRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ComposantController extends AbstractController
{
    /**
     * @Route("/composants", name="composants_liste")
     */
    public function index(ComposantRepository $repo): Response
    {

        $composants = $repo->findAll();
        return $this->render('composant/composant.html.twig', [
            'composants' => $composants,
        ]);
    }
}

templates/composant/composant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos composants{% endblock %}

{% block body %}
<div class="container">
   <h1 class="my-3">Voici les composants de nos médicaments !</h1>

      
      <div class="row">
         {% for composant in composants%} 
             {% set url = path('composants_liste', {'composant': composant}) %}

            <div class="col-md-4">
               <div class="card bg-light mb-1">
                  <a href="{{ url }}">
                     <img src="{{composant.image}}" alt="Image du composant"style="height: 200px; width: 100%; display: block;">
                  </a>
                       <div class="card-body">
                        <h4 class="card-text">
                           <a href="{{ url }}">
                              {{composant.nomComposant}}
                           </a>                  
                     </div>
               </div>
            </div>
         
        {% endfor %}
     </div>
</div>


{% endblock %}